import type { Project } from './types'
import { v4 as uuidv4 } from 'uuid'

export const DEFAULT_VALUES = {
  maklerProvision: 3.57,
  notarUndGrundbuch: 1.5,
  grundstueckAnteil: 20,
  zinssatz: 3.5,
  tilgung: 2,
  zinsbindung: 10,
  sondertilgung: 0,
  instandhaltungProQm: 10,
  verwaltungProEinheit: 25,
  nichtUmlegbareNebenkosten: 0,
  sonstigeKosten: 0,
  mietausfallwagnis: 2,
  nebenkostenProQm: 0,
  umlagefaehigAnteil: 70,
  persoenlicherSteuersatz: 42,
  zuVersteuerndesEinkommen: 60000,
  kirchensteuersatz: 9,
  afaBeweglichJahre: 10,
  wertsteigerung: 2,
  etfRendite: 5,
  customRendite: 5,
  hausgeldProMonat: 300,
  hausgeldInstandhaltungAnteil: 20,
  hausgeldVerwaltungAnteil: 15,
  projectionYears: 30,
} as const

export function createDefaultProject(overrides: Partial<Project> = {}): Project {
  const now = new Date().toISOString()
  return {
    id: uuidv4(),
    name: 'Neues Projekt',
    createdAt: now,
    updatedAt: now,
    propertyType: 'wohnung',
    address: '',
    lat: null,
    lng: null,
    bundesland: 'berlin',
    wohnflaeche: 70,
    baujahr: 1990,
    anzahlEinheiten: 1,
    kaufpreis: 250000,
    grundstueckAnteil: DEFAULT_VALUES.grundstueckAnteil,
    maklerProvision: DEFAULT_VALUES.maklerProvision,
    notarUndGrundbuch: DEFAULT_VALUES.notarUndGrundbuch,
    eigenkapital: 50000,
    zinssatz: DEFAULT_VALUES.zinssatz,
    tilgung: DEFAULT_VALUES.tilgung,
    zinsbindung: DEFAULT_VALUES.zinsbindung,
    sondertilgung: DEFAULT_VALUES.sondertilgung,
    zinsbindungPeriods: [],
    nutzungsart: 'vermietung',
    ersparteMiete: 0,
    isMehrfamilienhaus: false,
    wohnungen: [],
    monatsmieteKalt: 800,
    mietausfallwagnis: DEFAULT_VALUES.mietausfallwagnis,
    nebenkostenProQm: DEFAULT_VALUES.nebenkostenProQm,
    umlagefaehigAnteil: DEFAULT_VALUES.umlagefaehigAnteil,
    instandhaltungProQm: DEFAULT_VALUES.instandhaltungProQm,
    verwaltungProEinheit: DEFAULT_VALUES.verwaltungProEinheit,
    nichtUmlegbareNebenkosten: DEFAULT_VALUES.nichtUmlegbareNebenkosten,
    sonstigeKosten: DEFAULT_VALUES.sonstigeKosten,
    persoenlicherSteuersatz: DEFAULT_VALUES.persoenlicherSteuersatz,
    zuVersteuerndesEinkommen: DEFAULT_VALUES.zuVersteuerndesEinkommen,
    useProgressiveTax: false,
    kirchensteuer: false,
    kirchensteuersatz: DEFAULT_VALUES.kirchensteuersatz,
    beweglicheGegenstaende: 0,
    afaBeweglichJahre: DEFAULT_VALUES.afaBeweglichJahre,
    customAfaRate: null,
    marktKaufpreisProQm: null,
    marktMietpreisProQm: null,
    wertsteigerung: DEFAULT_VALUES.wertsteigerung,
    etfRendite: DEFAULT_VALUES.etfRendite,
    customRendite: DEFAULT_VALUES.customRendite,
    customInvestmentName: 'Anderes Investment',
    isInPortfolio: false,
    nettoJahresgehalt: 0,
    monatlicheAusgaben: 0,
    hausgeldModus: 'einzelposten',
    hausgeldProMonat: DEFAULT_VALUES.hausgeldProMonat,
    hausgeldInstandhaltungAnteil: DEFAULT_VALUES.hausgeldInstandhaltungAnteil,
    hausgeldVerwaltungAnteil: DEFAULT_VALUES.hausgeldVerwaltungAnteil,
    modernisierungen: [],
    nebenkostenPosten: [],
    ...overrides,
  }
}
